version: "3.9"

services:
  proxy:
    image: nginx:alpine
    ports:
      - "8080:80"
    networks:
      - busnet

  frontend:
    image: local/bus-frontend
    networks:
      - busnet

  backend:
    image: local/bus-backend
    networks:
      - busnet

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: busdb
    networks:
      - busnet

networks:
  busnet:
    external: true
